apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo

generatorOptions:
  disableNameSuffixHash: true

resources:
  - load-test.yaml

configMapGenerator:
  - name: lookup-mhs
    files:
      - test.js
      - mhs.txt
