apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../01_lookup_mhs

configMapGenerator:
  - name: lookup-mhs
    behavior: replace
    files:
      - test.js
      - mhs.txt

patchesStrategicMerge:
  - patch.yaml
