apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: lookup-mhs
spec:
  parallelism: 7
  arguments: '--out experimental-prometheus-rw --tag testId=lookup_mhs_gen'
  runner:
    image: '<published-image-url-goes-here>' # Add URL to the publicly accessible built image here.
