apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: simple
spec:
  parallelism: 1
  arguments: '--out experimental-prometheus-rw --tag testId=simple'
  runner:
    env:
      - name: K6_PROMETHEUS_RW_SERVER_URL
        value: http://prometheus-k8s.monitoring.svc.cluster.local:9090/api/v1/write
  cleanup: post
  script:
    configMap:
      name: simple-test
      file: test.js